service: besure-backend

plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-offline

custom:
  clinicTableName: clinics
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  ddb: ${file(./config.json):ddb}

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  profile: besure
  timeout: 10
  environment:
    CLINIC_TABLE_NAME: ${self:custom.clinicTableName}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CLINIC_TABLE_NAME}"

functions:
  update-table:
    handler: aggregator/handler.updateTable
  list:
    handler: api/list.list
    events:
      - http:
          path: clinics
          method: GET
          reqValidatorName: ListClinicsRequestValidator
          cors: true
          request:
            parameters:
              querystrings:
                latitude: true
                longitude: true
                radius: true
  get:
    handler: api/get.get
    events:
      - http:
          path: clinic/{id}
          method: GET
          cors: true

resources:
  Resources:
    ListClinicsRequestValidator:  
        Type: AWS::ApiGateway::RequestValidator
        Properties:
          Name: clinics-request-validator
          ValidateRequestBody: false
          ValidateRequestParameters: true
    ClinicTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ${self:custom.ddb.hashKeyAttributeName}
            AttributeType: N
          -
            AttributeName: ${self:custom.ddb.rangeKeyAttributeName}
            AttributeType: N
          -
            AttributeName: ${self:custom.ddb.geohashAttributeName}
            AttributeType: N
        KeySchema:
          -
            AttributeName: ${self:custom.ddb.hashKeyAttributeName}
            KeyType: HASH
          -
            AttributeName: ${self:custom.ddb.rangeKeyAttributeName}
            KeyType: RANGE
        LocalSecondaryIndexes:
          - 
            IndexName: geohashIndex
            KeySchema: 
              -
                AttributeName: ${self:custom.ddb.hashKeyAttributeName}
                KeyType: HASH
              -
                AttributeName: ${self:custom.ddb.geohashAttributeName}
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CLINIC_TABLE_NAME}