service: clinic-finder-backend

plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-offline

custom:
  clinicTableName: clinics
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
      forceInclude:
        - dynamodb-geo
  ddb: ${file(./env.json):ddb}

provider:
  name: aws
  region: us-west-2
  runtime: nodejs14.x
  profile: besure
  stage: ${opt:stage, 'beta'}
  timeout: 10
  environment:
    CLINIC_TABLE_NAME: ${self:custom.clinicTableName}-${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: 
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CLINIC_TABLE_NAME}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CLINIC_TABLE_NAME}/index/${self:custom.ddb.geohashIndexName}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CLINIC_TABLE_NAME}/index/${self:custom.ddb.idIndexName}"

functions:
  get:
    handler: src/get.get
    events:
      - http:
          path: clinics/{clinicId}
          method: GET
          reqValidatorName: clinicsRequestValidator
          cors: true
          request:
            parameters:
              paths:
                clinicId: true
  list:
    handler: src/list.list
    events:
      - http:
          path: clinics
          method: GET
          reqValidatorName: clinicsRequestValidator
          cors: true
          request:
            parameters:
              querystrings:
                latitude: true
                longitude: true
                radius: true

resources:
  Resources:
    clinicsRequestValidator:  
        Type: AWS::ApiGateway::RequestValidator
        Properties:
          Name: clinics-request-validator
          RestApiId: 
            Ref: ApiGatewayRestApi
          ValidateRequestBody: false
          ValidateRequestParameters: true
    ClinicTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ${self:custom.ddb.hashKeyAttributeName}
            AttributeType: N
          -
            AttributeName: ${self:custom.ddb.rangeKeyAttributeName}
            AttributeType: N
          -
            AttributeName: ${self:custom.ddb.geohashAttributeName}
            AttributeType: N
        KeySchema:
          -
            AttributeName: ${self:custom.ddb.hashKeyAttributeName}
            KeyType: HASH
          -
            AttributeName: ${self:custom.ddb.rangeKeyAttributeName}
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - 
            IndexName: ${self:custom.ddb.idIndexName}
            KeySchema: 
              -
                AttributeName: ${self:custom.ddb.rangeKeyAttributeName}
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - 
            IndexName: ${self:custom.ddb.geohashIndexName}
            KeySchema: 
              -
                AttributeName: ${self:custom.ddb.hashKeyAttributeName}
                KeyType: HASH
              -
                AttributeName: ${self:custom.ddb.geohashAttributeName}
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CLINIC_TABLE_NAME}